version: '3'

services:
  wireshark:
    image: utsa4953/wireshark
    container_name: wireshark
    privileged: true
    network_mode: "service:apache"
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    restart: unless-stopped

  nmap:
    image: utsa4953/nmap
    container_name: nmap
    tty: true

  apache:
    image: utsa4953/apache-app
    container_name: apache
    ports:
      - 80:80
      - 3000:3000
