version: '3'

services:
  wireshark:
    image: linuxserver/wireshark
    container_name: wireshark
    ports:
      - 3000:3000
    cap_add:
      - NET_ADMIN
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    restart: unless-stopped

  nmap:
    image: networkstatic/nmap
    container_name: nmap
    tty: true

  apache:
    image: utsa4953/apache-app
    container_name: apache
    ports:
      - 80:80

  