# Use base Ubuntu 18.04 image
FROM ubuntu:18.04
# Update and upgrade all repos and dependencies
RUN apt-get update -y
RUN apt-get upgrade -y
# Install Nmap
RUN apt-get install -y nmap
# Install ARP
RUN apt-get install -y arp-scan